# Generated by Django 4.2.30 on 2026-09-25 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RAPPEL_FACTURE', 'Rappel facture impayée'), ('PASSERELLE', 'Passerelle Mobile Money'), ('ANOMALIE', 'Anomalie détectée'), ('VALIDATION', 'Paiement à valider'), ('INFO', 'Information')], db_index=True, default='INFO', max_length=30)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(blank=True, default='', verbose_name='Message')),
                ('url', models.CharField(blank=True, default='', help_text='Lien interne (ex. /factures/) cliquable depuis la cloche.', max_length=200)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx')],
            },
        ),
    ]
