# Generated by Django 4.2.30 on 2026-09-25 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('TMONEY', 'T-Money'), ('MOOV', 'Moov Money'), ('FLOOZ', 'Flooz'), ('BANQUE', 'Banque'), ('ESPECES', 'Espèces')], max_length=20, verbose_name='Opérateur')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone débité')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('gateway_tx_id', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='ID opérateur')),
                ('status', models.CharField(choices=[('PENDING', 'En attente (push envoyé)'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('EXPIRED', 'Expiré')], db_index=True, default='PENDING', max_length=20)),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='Sandbox')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Réponse brute opérateur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gateway_transactions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_transactions', to='finance.invoice', verbose_name='Facture à encaisser')),
            ],
            options={
                'verbose_name': 'Transaction passerelle',
                'verbose_name_plural': 'Transactions passerelles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='finance_gat_status_24ccbf_idx')],
            },
        ),
    ]
