# Generated by Django 4.2.30 on 2026-09-27 23:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='Nom')),
                ('couleur', models.CharField(default='#063082', help_text="Couleur d'accent dans l'interface de vente.", max_length=7, verbose_name='Couleur (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouverte_at', models.DateTimeField(auto_now_add=True, verbose_name='Ouverte le')),
                ('fermee_at', models.DateTimeField(blank=True, null=True, verbose_name='Fermée le')),
                ('fond_caisse', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Fond de caisse')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], db_index=True, default='OUVERTE', max_length=10, verbose_name='Statut')),
                ('comptage_physique', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Comptage physique (espèces)')),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Écart (physique − théorique)')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note de clôture')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-ouverte_at'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Référence')),
                ('idempotence_key', models.UUIDField(db_index=True, help_text="Identifiant unique de vente généré par le client POS ; garantit qu'un replay réseau ne crée pas de doublon.", unique=True, verbose_name="Clé d'idempotence")),
                ('client_name', models.CharField(blank=True, default='', help_text='Vide = client anonyme. Un client enregistré permet le suivi de fiabilité.', max_length=200, verbose_name='Client (facultatif)')),
                ('client_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone client')),
                ('statut', models.CharField(choices=[('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], db_index=True, default='VALIDEE', max_length=10, verbose_name='Statut')),
                ('total_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('remise_panier', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Remise panier')),
                ('rendu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Monnaie rendue')),
                ('ticket_imprime', models.BooleanField(default=False, help_text="False = ticket en file d'impression (mode dégradé sans imprimante).", verbose_name='Ticket imprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='caisse.sessioncaisse', verbose_name='Session')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente POS',
                'verbose_name_plural': 'Ventes POS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Référence')),
                ('ean', models.CharField(blank=True, db_index=True, default='', help_text='13 chiffres ; scannable caméra mobile ou lecteur USB (POS-03).', max_length=13, verbose_name='Code-barres EAN-13')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('unite', models.CharField(default='pièce', max_length=20, verbose_name='Unité de vente')),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de vente TTC (FCFA)')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux de TVA (%)')),
                ('cout_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Coût d'achat (optionnel)")),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Stock')),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name="Seuil d'alerte stock")),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/%Y/%m/', verbose_name='Image')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='caisse.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Catalogue produits',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='PaiementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen', models.CharField(choices=[('ESPECES', 'Espèces'), ('TMONEY', 'T-Money'), ('MOOV', 'Moov Money'), ('FLOOZ', 'Flooz'), ('CARTE', 'Carte bancaire (terminal externe)')], max_length=10, verbose_name='Moyen')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('reference', models.CharField(blank=True, default='', help_text='Référence opérateur saisie manuellement si la passerelle est indisponible.', max_length=60, verbose_name='N° de transaction (repli manuel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='caisse.vente')),
            ],
            options={
                'verbose_name': 'Paiement de vente',
                'verbose_name_plural': 'Paiements de vente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VENTE_ESPECES', 'Vente en espèces'), ('DEPOT', 'Dépôt de sécurisation'), ('RETRAIT', 'Retrait (fonds)'), ('DEPENSE', 'Dépense au comptant'), ('ECART', 'Écart de clôture')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, help_text="Positif = entrée d'espèces, négatif = sortie.", max_digits=12, verbose_name='Montant (FCFA)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_caisse', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='caisse.sessioncaisse', verbose_name='Session')),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='caisse.vente', verbose_name='Vente liée')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation (figée)')),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('prix_unitaire_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva_taux', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('remise_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Remise ligne (%)')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total ligne TTC')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='caisse.produit', verbose_name='Produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='caisse.vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['statut', 'created_at'], name='caisse_vent_statut_367dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['statut', 'ouverte_at'], name='caisse_sess_statut_62059a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessioncaisse',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'OUVERTE')), fields=('vendeur',), name='unique_session_ouverte_par_vendeur'),
        ),
    ]
